create table if not exists public.agent_turn_queue (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('playground', 'whatsapp')),
  status text not null default 'waiting' check (status in ('waiting', 'processing', 'completed', 'failed', 'abandoned', 'expired')),
  position bigint generated by default as identity not null,
  lock_token uuid,
  enqueued_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  expires_at timestamptz not null default (now() + interval '2 minutes'),
  error text
);

create index if not exists agent_turn_queue_conversation_status_position_idx
on public.agent_turn_queue (user_id, channel, status, position);

create index if not exists agent_turn_queue_expires_idx
on public.agent_turn_queue (expires_at)
where status in ('waiting', 'processing');

alter table public.agent_turn_queue enable row level security;

drop policy if exists "Users can view their own agent turn queue" on public.agent_turn_queue;
create policy "Users can view their own agent turn queue"
on public.agent_turn_queue
for select
to authenticated
using (auth.uid() = user_id);

create table if not exists public.agent_conversation_locks (
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('playground', 'whatsapp')),
  queue_item_id uuid references public.agent_turn_queue(id) on delete cascade,
  lock_token uuid not null,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null,
  primary key (user_id, channel)
);

create index if not exists agent_conversation_locks_expires_idx
on public.agent_conversation_locks (expires_at);

alter table public.agent_conversation_locks enable row level security;

drop policy if exists "Users can view their own agent conversation locks" on public.agent_conversation_locks;
create policy "Users can view their own agent conversation locks"
on public.agent_conversation_locks
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.enqueue_agent_turn(
  target_user_id uuid,
  target_channel text,
  turn_ttl_seconds integer default 120
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  queued_id uuid;
  queued_position bigint;
  safe_ttl_seconds integer := least(greatest(coalesce(turn_ttl_seconds, 120), 30), 300);
begin
  if target_user_id is null then
    raise exception 'target_user_id is required.'
      using errcode = '22023';
  end if;

  if target_channel not in ('playground', 'whatsapp') then
    raise exception 'Invalid channel: %', target_channel
      using errcode = '22023';
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin(auth.uid())
     and auth.uid() is distinct from target_user_id then
    raise exception 'Not allowed to enqueue agent turn for another user.'
      using errcode = '42501';
  end if;

  update public.agent_turn_queue
  set status = 'expired',
      finished_at = now(),
      error = coalesce(error, 'Turn expired before processing.')
  where user_id = target_user_id
    and channel = target_channel
    and status in ('waiting', 'processing')
    and expires_at <= now();

  delete from public.agent_conversation_locks
  where user_id = target_user_id
    and channel = target_channel
    and expires_at <= now();

  insert into public.agent_turn_queue (
    user_id,
    channel,
    expires_at
  )
  values (
    target_user_id,
    target_channel,
    now() + make_interval(secs => safe_ttl_seconds)
  )
  returning id, position into queued_id, queued_position;

  return jsonb_build_object(
    'queueId', queued_id,
    'position', queued_position
  );
end;
$$;

revoke all on function public.enqueue_agent_turn(uuid, text, integer) from public;
grant execute on function public.enqueue_agent_turn(uuid, text, integer) to authenticated, service_role;

create or replace function public.claim_agent_turn(
  queue_item_id uuid,
  lock_ttl_seconds integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.agent_turn_queue%rowtype;
  head_id uuid;
  requested_token uuid := gen_random_uuid();
  claimed_token uuid;
  safe_lock_ttl_seconds integer := least(greatest(coalesce(lock_ttl_seconds, 90), 30), 300);
begin
  select *
  into item
  from public.agent_turn_queue
  where id = claim_agent_turn.queue_item_id
  for update;

  if not found then
    return jsonb_build_object('claimed', false, 'reason', 'missing_queue_item');
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin(auth.uid())
     and auth.uid() is distinct from item.user_id then
    raise exception 'Not allowed to claim agent turn for another user.'
      using errcode = '42501';
  end if;

  update public.agent_turn_queue
  set status = 'expired',
      finished_at = now(),
      error = coalesce(error, 'Turn expired before processing.')
  where user_id = item.user_id
    and channel = item.channel
    and status in ('waiting', 'processing')
    and expires_at <= now();

  delete from public.agent_conversation_locks
  where user_id = item.user_id
    and channel = item.channel
    and expires_at <= now();

  select *
  into item
  from public.agent_turn_queue
  where id = claim_agent_turn.queue_item_id
  for update;

  if item.status <> 'waiting' then
    return jsonb_build_object('claimed', false, 'reason', item.status);
  end if;

  select id
  into head_id
  from public.agent_turn_queue
  where user_id = item.user_id
    and channel = item.channel
    and status = 'waiting'
  order by position asc
  limit 1;

  if head_id is distinct from claim_agent_turn.queue_item_id then
    return jsonb_build_object('claimed', false, 'reason', 'not_queue_head');
  end if;

  insert into public.agent_conversation_locks (
    user_id,
    channel,
    queue_item_id,
    lock_token,
    acquired_at,
    expires_at
  )
  values (
    item.user_id,
    item.channel,
    item.id,
    requested_token,
    now(),
    now() + make_interval(secs => safe_lock_ttl_seconds)
  )
  on conflict (user_id, channel) do update
  set queue_item_id = excluded.queue_item_id,
      lock_token = excluded.lock_token,
      acquired_at = excluded.acquired_at,
      expires_at = excluded.expires_at
  where public.agent_conversation_locks.expires_at <= now()
  returning lock_token into claimed_token;

  if claimed_token is null then
    return jsonb_build_object('claimed', false, 'reason', 'conversation_locked');
  end if;

  update public.agent_turn_queue
  set status = 'processing',
      lock_token = claimed_token,
      started_at = now(),
      expires_at = now() + make_interval(secs => safe_lock_ttl_seconds)
  where id = claim_agent_turn.queue_item_id;

  return jsonb_build_object(
    'claimed', true,
    'lockToken', claimed_token
  );
end;
$$;

revoke all on function public.claim_agent_turn(uuid, integer) from public;
grant execute on function public.claim_agent_turn(uuid, integer) to authenticated, service_role;

create or replace function public.extend_agent_turn_lock(
  queue_item_id uuid,
  provided_lock_token uuid,
  lock_ttl_seconds integer default 90
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.agent_turn_queue%rowtype;
  renewed_expires_at timestamptz;
  safe_lock_ttl_seconds integer := least(greatest(coalesce(lock_ttl_seconds, 90), 30), 300);
begin
  select *
  into item
  from public.agent_turn_queue
  where id = extend_agent_turn_lock.queue_item_id
  for update;

  if not found then
    return false;
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin(auth.uid())
     and auth.uid() is distinct from item.user_id then
    raise exception 'Not allowed to extend agent turn for another user.'
      using errcode = '42501';
  end if;

  if item.status <> 'processing' or item.lock_token is distinct from provided_lock_token then
    return false;
  end if;

  renewed_expires_at := now() + make_interval(secs => safe_lock_ttl_seconds);

  update public.agent_conversation_locks
  set expires_at = renewed_expires_at
  where user_id = item.user_id
    and channel = item.channel
    and public.agent_conversation_locks.queue_item_id = item.id
    and lock_token = provided_lock_token;

  if not found then
    return false;
  end if;

  update public.agent_turn_queue
  set expires_at = renewed_expires_at
  where id = extend_agent_turn_lock.queue_item_id;

  return true;
end;
$$;

revoke all on function public.extend_agent_turn_lock(uuid, uuid, integer) from public;
grant execute on function public.extend_agent_turn_lock(uuid, uuid, integer) to authenticated, service_role;

create or replace function public.finish_agent_turn(
  queue_item_id uuid,
  provided_lock_token uuid,
  final_status text default 'completed',
  error_text text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.agent_turn_queue%rowtype;
begin
  if final_status not in ('completed', 'failed') then
    raise exception 'Invalid final status: %', final_status
      using errcode = '22023';
  end if;

  select *
  into item
  from public.agent_turn_queue
  where id = finish_agent_turn.queue_item_id
  for update;

  if not found then
    return false;
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin(auth.uid())
     and auth.uid() is distinct from item.user_id then
    raise exception 'Not allowed to finish agent turn for another user.'
      using errcode = '42501';
  end if;

  if item.status <> 'processing' or item.lock_token is distinct from provided_lock_token then
    return false;
  end if;

  update public.agent_turn_queue
  set status = final_status,
      finished_at = now(),
      error = error_text
  where id = finish_agent_turn.queue_item_id;

  delete from public.agent_conversation_locks
  where user_id = item.user_id
    and channel = item.channel
    and public.agent_conversation_locks.queue_item_id = item.id
    and lock_token = provided_lock_token;

  return true;
end;
$$;

revoke all on function public.finish_agent_turn(uuid, uuid, text, text) from public;
grant execute on function public.finish_agent_turn(uuid, uuid, text, text) to authenticated, service_role;

create or replace function public.abandon_agent_turn(
  queue_item_id uuid,
  error_text text default 'Turn abandoned before processing.'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.agent_turn_queue%rowtype;
begin
  select *
  into item
  from public.agent_turn_queue
  where id = abandon_agent_turn.queue_item_id
  for update;

  if not found then
    return false;
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin(auth.uid())
     and auth.uid() is distinct from item.user_id then
    raise exception 'Not allowed to abandon agent turn for another user.'
      using errcode = '42501';
  end if;

  if item.status <> 'waiting' then
    return false;
  end if;

  update public.agent_turn_queue
  set status = 'abandoned',
      finished_at = now(),
      error = left(coalesce(error_text, 'Turn abandoned before processing.'), 240)
  where id = abandon_agent_turn.queue_item_id;

  return true;
end;
$$;

revoke all on function public.abandon_agent_turn(uuid, text) from public;
grant execute on function public.abandon_agent_turn(uuid, text) to authenticated, service_role;
